# Generated by Django 3.0.5 on 2020-05-02 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herokuapp', '0003_auto_20200501_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='imagen',
            field=models.URLField(),
        ),
    ]
